# Generated by Django 5.2.9 on 2025-12-19 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SousGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du sous-groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('jour_reference', models.DateField(help_text='Date grégorienne servant de point de départ pour le calcul du cycle', verbose_name='Jour de référence')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Sous-groupe',
                'verbose_name_plural': 'Sous-groupes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='JourCulturel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du jour')),
                ('ordre', models.IntegerField(help_text='Position du jour dans le cycle (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre dans le cycle')),
                ('sacre', models.BooleanField(default=False, help_text='Si coché, ce jour sera affiché en rouge', verbose_name='Jour sacré/interdit')),
                ('sous_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_culturels', to='calendrier.sousgroupe', verbose_name='Sous-groupe')),
            ],
            options={
                'verbose_name': 'Jour culturel',
                'verbose_name_plural': 'Jours culturels',
                'ordering': ['sous_groupe', 'ordre'],
                'unique_together': {('sous_groupe', 'nom'), ('sous_groupe', 'ordre')},
            },
        ),
    ]
