# Generated by Django 5.2.9 on 2025-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone_whatsapp', models.CharField(blank=True, help_text='Format: +225XXXXXXXXX', max_length=20, verbose_name='Numéro WhatsApp')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notifications_email', models.BooleanField(default=True, help_text="Recevoir un email la veille de l'anniversaire", verbose_name='Activer les notifications par email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
